name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MinGW
      run: sudo apt-get install -y mingw-w64

    - name: Compile optimized
      run: x86_64-w64-mingw32-gcc -Os -s main.c -o taskmgr_hotkey.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: taskmgr-hotkey
        path: taskmgr_hotkey.exe
